version: 0.2

env:
  variables:
    REGION: "sa-east-1"
    ACCOUNT_ID: "248189947068"
    CLUSTER_NAME: "sas-6881323-eks"
    REPOSITORY: "dataiesb-site"
    DEPLOYMENT_NAME: "dataiesb-app"
    CONTAINER_NAME: "dataiesb-container"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 248189947068.dkr.ecr.us-east-1.amazonaws.com

      - REPOSITORY_URI=248189947068.dkr.ecr.us-east-1.amazonaws.com/report-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f Dockerfile-EKS .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Build completed on `date`
      - echo "Copying all files from report-manual-sync/ to S3..."
      - aws s3 cp src/ s3://dataiesb/ --recursive
      - echo "S3 copy complete."

artifacts:
  files:
    - '**/*'

