version: 0.2

env:
  variables:
    REGION: "sa-east-1"
    ACCOUNT_ID: "248189947068"
    REPOSITORY: "dataiesb-site"
    DEPLOYMENT_NAME: "dataiesb-app"
    CONTAINER_NAME: "dataiesb-container"
    S3_BUCKET: "dataiesb"  # Add this variable to define the target S3 bucket

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo Preparing to upload files to S3 in region $REGION...
      - aws --version
      - echo Using S3 bucket $S3_BUCKET for file upload.

  build:
    commands:
      - echo Uploading files to S3 bucket $S3_BUCKET...
      - aws s3 cp src/ s3://$S3_BUCKET/ --recursive

  post_build:
    commands:
      - echo "S3 copy complete."

artifacts:
  files:
    - '**/*'

