version: 0.2

env:
  variables:
    REGION: "sa-east-1"
    S3_BUCKET: "dataiesb"
    CLOUDFRONT_DISTRIBUTION_ID: "E371T2F886B5KI"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Starting deployment to production..."
      - echo "Region: $REGION"
      - echo "S3 Bucket: $S3_BUCKET"
      - echo "CloudFront Distribution: $CLOUDFRONT_DISTRIBUTION_ID"
      - aws --version

  build:
    commands:
      - echo "Uploading files to S3 bucket..."
      - aws s3 sync src/ s3://$S3_BUCKET/ --region $REGION --delete --exclude "*.sh" --exclude "*.json" --exclude ".git/*" --exclude ".github/*" --exclude "*.md"
      - echo "Files successfully synced to S3"

  post_build:
    commands:
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed successfully!"
      - echo "Site URL: https://dataiesb.com"

artifacts:
  files:
    - '**/*'
  base-directory: 'src'
