version: 0.2

# Unified buildspec for both dev and prod branches
# Automatically detects branch and deploys to appropriate environment

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Detecting branch and environment..."
      - |
        if [ "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/prod" ] || [ "$CODEBUILD_SOURCE_VERSION" = "prod" ]; then
          export ENVIRONMENT="production"
          export AWS_REGION="sa-east-1"
          export S3_BUCKET="dataiesb"
          export CLOUDFRONT_ID="E371T2F886B5KI"
          export SITE_URL="https://dataiesb.com"
        else
          export ENVIRONMENT="development"
          export AWS_REGION="us-east-1"
          export S3_BUCKET="dev-dataiesb"
          export CLOUDFRONT_ID="E142Z1CPAKR8S8"
          export SITE_URL="https://d2v66tm8wx23ar.cloudfront.net"
        fi
      - echo "Starting $ENVIRONMENT deployment..."
      - echo "Environment: $ENVIRONMENT"
      - echo "Region: $AWS_REGION"
      - echo "S3 Bucket: $S3_BUCKET"
      - echo "CloudFront Distribution: $CLOUDFRONT_ID"
      - echo "Site URL: $SITE_URL"
      - aws --version

  build:
    commands:
      - echo "Uploading files to $ENVIRONMENT S3 bucket..."
      - aws s3 sync src/ s3://$S3_BUCKET/ --region $AWS_REGION --delete --exclude "*.sh" --exclude "*.json" --exclude ".git/*" --exclude ".github/*" --exclude "*.md" --exclude "test-*" --exclude "*-test.*"
      - echo "Files successfully synced to $ENVIRONMENT S3"

  post_build:
    commands:
      - echo "Invalidating $ENVIRONMENT CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo "$ENVIRONMENT deployment completed successfully"
      - echo "$ENVIRONMENT site: $SITE_URL"

artifacts:
  files:
    - '**/*'
  base-directory: 'src'
