version: 0.2

# Production buildspec for main branch deployment

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Starting production deployment from main branch..."
      - export ENVIRONMENT="production"
      - export AWS_REGION="sa-east-1"
      - export S3_BUCKET="dataiesb"
      - export CLOUDFRONT_ID="E371T2F886B5KI"
      - export SITE_URL="https://dataiesb.com"
      - echo "Environment is $ENVIRONMENT"
      - echo "Region is $AWS_REGION"
      - echo "S3 Bucket is $S3_BUCKET"
      - echo "CloudFront Distribution is $CLOUDFRONT_ID"
      - echo "Site URL is $SITE_URL"
      - aws --version

  build:
    commands:
      - echo "Uploading files to production S3 bucket..."
      - aws s3 sync src/ s3://$S3_BUCKET/ --region $AWS_REGION --delete --exclude "*.sh" --exclude "*.json" --exclude ".git/*" --exclude ".github/*" --exclude "*.md" --exclude "test-*" --exclude "*-test.*"
      - echo "Files successfully synced to production S3"

  post_build:
    commands:
      - echo "Invalidating production CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo "Production deployment completed successfully"
      - echo "Production site is $SITE_URL"

artifacts:
  files:
    - '**/*'
  base-directory: 'src'
