version: 0.2

env:
  variables:
    REGION: "sa-east-1"
    ACCOUNT_ID: "248189947068"
    CLUSTER_NAME: "sas-6881323-eks"
    REPOSITORY: "dataiesb-site"
    DEPLOYMENT_NAME: "dataiesb-app"
    CONTAINER_NAME: "dataiesb-container"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-04-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - echo Installing AWS CLI...
      - pip install --upgrade awscli

  pre_build:
    commands:
      - export REGION=sa-east-1
      - export ACCOUNT_ID=248189947068
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Configuring kubectl for EKS...
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Updating deployment in EKS...
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG -n default
      - kubectl rollout status deployment/$DEPLOYMENT_NAME -n default

