version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Starting deployment..."
      - aws --version

  build:
    commands:
      - echo "Uploading files to S3..."
      - aws s3 sync src/ s3://dataiesb/ --region sa-east-1 --delete

  post_build:
    commands:
      - echo "Invalidating CloudFront..."
      - aws cloudfront create-invalidation --distribution-id E371T2F886B5KI --paths "/*"
      - echo "Deployment completed!"

artifacts:
  files:
    - '**/*'
  base-directory: 'src'
