apiVersion: v1
kind: Service
metadata:
  name: dataiesb-svc
  labels:
    app: dataiesb-app
spec:
  type: ClusterIP
  selector:
    app: dataiesb-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http

